### ISSUE TITLE
TypeError: crypto.randomUUID

### ISSUE THREAD

**Issue by baszoetekouw** [SURFscz/SBS#1128]
Seems a regression, because this was fixed before in #611 
```
{"userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/15.0 Safari/605.1.15", "message": "TypeError: crypto.randomUUID is not a function. (In 'crypto.randomUUID()', 'crypto.randomUUID' is undefined)", "url": "https://sram.surf.nl/static/js/main.091b9fec.js", "line": 2, "col": 850401, "error": "crypto.randomUUID is not a function. (In 'crypto.randomUUID()', 'crypto.randomUUID' is undefined)", "stack": "ks@https://sram.surf.nl/static/js/main.091b9fec.js:2:2498401\nqi@https://sram.surf.nl/static/js/main.091b9fec.js:2:800883\nqc@https://sram.surf.nl/static/js/main.091b9fec.js:2:857997\nvl@https://sram.surf.nl/static/js/main.091b9fec.js:2:847103\nzl@https://sram.surf.nl/static/js/main.091b9fec.js:2:847031\nMl@https://sram.surf.nl/static/js/main.091b9fec.js:2:846894\nil@https://sram.surf.nl/static/js/
 main.091b9fec.js:2:843674\nal@https://sram.surf.nl/static/js/main.091b9fec.js:2:842225\nal@[native code]\nA@https://sram.surf.nl/static/js/main.091b9fec.js:2:1102352\nS@https://sram.surf.nl/static/js/main.091b9fec.js:2:1102886\n@https://sram.surf.nl/static/js/main.091b9fec.js:2:1260012\nW@https://sram.surf.nl/static/js/main.091b9fec.js:2:1259781\nR@https://sram.surf.nl/static/js/main.091b9fec.js:2:1259840"}
```

**Comment by baszoetekouw** [comment]
hard to test.  Let's monitor if it reappears in the error reports after the release.
